### ISSUE TITLE
remove any reference of me in this you can have it

### ISSUE THREAD

**Issue by ghost** [ProjectDonetsk/MW_Devmenu-main#1]
Hello, I have recently noticed that this repository is practically a complete copy of my original repository. My original repository does not have a license and therefore it is technically mine according to copyright law. 

Edit: I just really don't wanna be accociated with donetsk
Additionally, I do not believe you are allowed to take my copyrighted work and add a license

Absolutely no changes were made to the menu

**Comment by million1156** [comment]
> Hello, I have recently noticed that this repository is practically a complete copy of my original repository. My original repository does not have a license and therefore it is technically mine according to copyright law.
> 
> Additionally, I do not believe you are allowed to take my copyrighted work and add a license
> 
> Absolutely no changes were made to the menu

you have 0 right to proclaim that a **MOD MENU** for a game that prohibits a mod menu or even modification of the game for that manner is your copyright... its like saying you remixing a song makes that your song now.. it doesnt LMAO

**Comment by ghost** [comment]
Dude I just wanna be disaccociated with Donetsk and startrooper.

Also, this is a carbon copy of what was on my GitHub, your analogy doesn't make sense. I doubt that you can add a license to it either

**Comment by million1156** [comment]
> Dude I just wanna be disaccociated with Donetsk and startrooper.
> 
> Also, this is a carbon copy of what was on my GitHub, your analogy doesn't make sense. I doubt that you can add a license to it either

uh. buddy?
![image](https://github.com/ProjectDonetsk/MW_Devmenu-main/assets/91338231/5c087277-cadd-4dc1-8aa2-be3df699f7c3)
you kinda had a license.. a license that permitted reuploading anyway.. LMAO
![image](https://github.com/ProjectDonetsk/MW_Devmenu-main/assets/91338231/61267231-d75f-4592-bcc9-8fe0536df1bb)

**Comment by ghost** [comment]
Regardless if that license was there when it was literally stolen (it wasn't), it doesn't mean it can be relicensed.
And again, it's a carbon copy

**Comment by million1156** [comment]
> Regardless if that license was there when it was literally stolen (it wasn't), it doesn't mean it can be relicensed. And again, it's a carbon copy

A: carbon copy doesnt matter. cc 1.0 still says you can "remix, transform, and build upon the material for any purpose". doesnt matter if nothing was changed.
B: while yes it wasn't there when the repo was cloned, the fact that you added a license makes all your code (future & past) fall under that license (unless there was a license BEFORE all of this happened)
C: it absolutely does mean you can relicense. all the team needs to do is provide a link to the cc 1.0 website. and thats it. lmao.

**Comment by ghost** [comment]
That is reasonable
Please remove my name then, I do not want to be accociated with the shit show that donetsk

**Comment by million1156** [comment]
> That is reasonable Please remove my name then, I do not want to be accociated with the shit show that donetsk

i don't manage anything, so i cant really do that. good luck with any future projects though ig

**Comment by ghost** [comment]
Okay then

I should probably reread about copyright

**Comment by MatrixMMOfficial** [comment]
💀

**Comment by MatrixMMOfficial** [comment]
Yeah okay doxxer

**Comment by ZEROPOINTBRUH** [comment]
# @CrazySniperCatt0 
You have been banned from submitting issues, submitting requests, or making any changes to our organization repositories.

Please take your pitty elsewhere.
Good day to you.
